var config = {};
config.env = "dev";
config.httpsPort = 444;
//config.xplorifyDb = "mongodb://XplorifyAdmin:Xp12345!@live.xplorify.net:1212/xplorifydb";
config.xplorifyDb = "mongodb://localhost/xplorifydb";
config.serverUrl = "https://localhost:444";
config.freeGeoIpUrl = "http://138.201.48.14:1234/json";
config.application = {code: "blog", url: "https://blog.xplorify.mk"}
module.exports = config;