var config = {};
config.env = "tst";
config.httpsPort = 444;
config.jwtSecret = "pvpnCCZfwOF85pBjbOebZiYIDhZ3w9LZrKwBZ7152K89mPCOHtbRlmr5Z91ci4L";
config.xplorifyDb = "mongodb://XplorifyAdmin:Xp12345!@live.xplorify.net:1212/xplorifydb";
config.serverUrl = "https://live.xplorify.net";
config.freeGeoIpUrl = "http://138.201.48.14/json";
config.application = { code: "blog", url: "https://blog.xplorify.mk" };
module.exports = config;